source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

target 'PlayAppStore'  do

pod 'Masonry'
pod 'TPKeyboardAvoiding'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'QMUIKit', '~>1.2'
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~>3.8'
pod "DownloadButton"
pod 'PlayAppStoreSDK'
pod 'MJRefresh'
end
